export const SEED_LEADERS: { name: string; colors: string[] }[] = [
  { name: 'Monkey D. Luffy', colors: ['red'] },
  { name: 'Roronoa Zoro', colors: ['green'] },
  { name: 'Nami', colors: ['blue'] },
  { name: 'Usopp', colors: ['green', 'yellow'] },
  { name: 'Sanji', colors: ['blue'] },
  { name: 'Tony Tony Chopper', colors: ['green'] },
  { name: 'Nico Robin', colors: ['blue', 'purple'] },
  { name: 'Franky', colors: ['blue'] },
  { name: 'Donquixote Doflamingo', colors: ['purple'] },
  { name: 'Charlotte Katakuri', colors: ['yellow'] },
  { name: 'Trafalgar Law', colors: ['red', 'green'] },
  { name: 'Kaido', colors: ['purple', 'black'] },
  { name: 'Big Mom', colors: ['yellow'] },
  { name: 'Shanks', colors: ['red'] },
  { name: 'Boa Hancock', colors: ['purple'] },
  { name: 'Crocodile', colors: ['blue', 'black'] },
  { name: 'Rob Lucci', colors: ['black'] },
  { name: 'Sakazuki (Akainu)', colors: ['black'] },
  { name: 'Kuzan (Aokiji)', colors: ['blue'] },
  { name: 'Eustass Kid', colors: ['red', 'purple'] },
  { name: 'Portgas D. Ace', colors: ['red'] },
  { name: 'Yamato', colors: ['green', 'yellow'] },
  { name: 'Enel', colors: ['blue', 'yellow'] },
  { name: 'Gecko Moria', colors: ['black'] },
  { name: 'Jewelry Bonney', colors: ['green'] },
];

export const SEED_SETS: { name: string; code: string }[] = [
  { name: 'Romance Dawn', code: 'OP01' },
  { name: 'Paramount War', code: 'OP02' },
  { name: 'Pillars of Strength', code: 'OP03' },
  { name: 'Kingdoms of Intrigue', code: 'OP04' },
  { name: 'Awakening of the New Era', code: 'OP05' },
  { name: 'Wings of the Captain', code: 'OP06' },
  { name: '500 Years in the Future', code: 'OP07' },
  { name: 'Two Legends', code: 'OP08' },
];
