export const SEED_LEADERS: { name: string; colors: string[] }[] = [
  { name: 'Monkey D. Luffy', colors: ['red'] },
  { name: 'Roronoa Zoro', colors: ['green'] },
  { name: 'Nami', colors: ['blue'] },
  { name: 'Usopp', colors: ['green', 'yellow'] },
  { name: 'Sanji', colors: ['blue'] },
  { name: 'Tony Tony Chopper', colors: ['green'] },
  { name: 'Nico Robin', colors: ['blue', 'purple'] },
  { name: 'Franky', colors: ['blue'] },
  { name: 'Donquixote Doflamingo', colors: ['purple'] },
  { name: 'Charlotte Katakuri', colors: ['yellow'] },
  { name: 'Trafalgar Law', colors: ['red', 'green'] },
  { name: 'Kaido', colors: ['purple', 'black'] },
  { name: 'Big Mom', colors: ['yellow'] },
  { name: 'Shanks', colors: ['red'] },
  { name: 'Boa Hancock', colors: ['purple'] },
  { name: 'Crocodile', colors: ['blue', 'black'] },
  { name: 'Rob Lucci', colors: ['black'] },
  { name: 'Sakazuki (Akainu)', colors: ['black'] },
  { name: 'Kuzan (Aokiji)', colors: ['blue'] },
  { name: 'Eustass Kid', colors: ['red', 'purple'] },
  { name: 'Portgas D. Ace', colors: ['red'] },
  { name: 'Yamato', colors: ['green', 'yellow'] },
  { name: 'Enel', colors: ['blue', 'yellow'] },
  { name: 'Gecko Moria', colors: ['black'] },
  { name: 'Jewelry Bonney', colors: ['green'] },
];

export const SEED_METAS: { name: string; code: string }[] = [
  { name: 'OP01 Romance Dawn', code: 'OP01' },
  { name: 'OP02 Paramount War', code: 'OP02' },
  { name: 'OP03 Pillars of Strength', code: 'OP03' },
  { name: 'OP04 Kingdoms of Intrigue', code: 'OP04' },
  { name: 'OP05 Awakening of the New Era', code: 'OP05' },
  { name: 'OP06 Wings of the Captain', code: 'OP06' },
  { name: 'OP07 500 Years in the Future', code: 'OP07' },
  { name: 'OP08 Two Legends', code: 'OP08' },
  { name: 'OP09', code: 'OP09' },
  { name: 'OP10', code: 'OP10' },
  { name: 'OP11', code: 'OP11' },
  { name: 'OP12', code: 'OP12' },
  { name: 'OP13', code: 'OP13' },
  { name: 'OP14', code: 'OP14' },
  { name: 'OP15', code: 'OP15' },
  { name: 'OP16', code: 'OP16' },
];
