/**
 * Regenerates the real OPTCG reference data from https://optcgapi.com.
 *
 *   npx tsx scripts/build-leader-data.ts
 *
 * Run this by hand when a new set drops — it is deliberately NOT part of
 * `next build`, so the app has no runtime dependency on optcgapi (their docs ask
 * callers not to hammer the API). Everything it produces is committed:
 *
 *   src/db/seed-data.ts      leaders (name/colors/setCode) + metas
 *   src/lib/leader-images.ts the set of codes that have bundled art
 *   public/leaders/*.webp    240px-wide card thumbnails
 *
 * Note: every public source of OPTCG card art — optcgapi, Limitless, and
 * Bandai's own card list — serves the same SAMPLE-watermarked promotional
 * scans. There is no clean-art source, so the watermark is expected.
 */
import { mkdir, writeFile, access } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

const API = 'https://optcgapi.com/api';
const ROOT = path.resolve(import.meta.dirname, '..');
const IMAGE_DIR = path.join(ROOT, 'public/leaders');
const IMAGE_WIDTH = 240;

/** The subset of an optcgapi card row this script relies on. */
type ApiCard = {
  card_set_id: string;
  card_name: string;
  card_color: string;
  card_type: string;
  card_image: string;
};
type ApiSet = { set_id: string; set_name: string };
type ApiDeck = { structure_deck_id: string; structure_deck_name: string };

async function getJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} → ${res.status}`);
  return res.json() as Promise<T>;
}

/** Parallels and alternate arts reprint an existing card_set_id — prefer the base printing. */
const isVariant = (c: ApiCard) => /\((?:Parallel|Alternate Art)\)/.test(c.card_name);

/**
 * Bandai's card_name carries a trailing disambiguator and packs initials against
 * the surrounding names. We show the set code separately, so strip the
 * disambiguator and unpack the dots:
 *   "Monkey.D.Luffy (003)"      → "Monkey D. Luffy"
 *   "Trafalgar Law - OP14-001"  → "Trafalgar Law"
 *   "Eustass\"Captain\"Kid (099)" → "Eustass \"Captain\" Kid"
 */
export function cleanLeaderName(raw: string): string {
  let n = raw
    .replace(/\s*\((?:\d+|SPR|Parallel|Alternate Art|[A-Z]{2,4}\d{2}-\d+)\)/g, '')
    .replace(/\s*-\s*[A-Z]{2,4}\d{2}-\d+\s*$/, '')
    .trim();

  // A dot after a lone initial keeps it ("D." ); a dot after a full word is just
  // a missing space ("Edward.Newgate" → "Edward Newgate").
  if (n.includes('.')) {
    const parts = n.split('.');
    n = parts
      .map((p, i) => (i === parts.length - 1 ? p : p + (p.length === 1 ? '. ' : ' ')))
      .join('');
  }

  return n.replace(/"([^"]+)"/g, ' "$1" ').replace(/\s+/g, ' ').trim();
}

/** "Green Red" → ['green','red'], which are exactly the LEADER_COLOR_HEX keys. */
const parseColors = (raw: string) => raw.trim().split(/\s+/).filter(Boolean).map((c) => c.toLowerCase());

async function exists(p: string) {
  try { await access(p); return true; } catch { return false; }
}

/** Downloads a card image and writes a width-constrained WebP. Skips work already done. */
async function fetchImage(card: ApiCard): Promise<boolean> {
  const out = path.join(IMAGE_DIR, `${card.card_set_id}.webp`);
  if (await exists(out)) return false;
  const res = await fetch(card.card_image);
  if (!res.ok) throw new Error(`image ${card.card_set_id} → ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  await sharp(buf).resize({ width: IMAGE_WIDTH }).webp({ quality: 78 }).toFile(out);
  return true;
}

const BANNER = (src: string) =>
  `// GENERATED by scripts/build-leader-data.ts from ${src} — do not edit by hand.\n`;

async function main() {
  console.log('Fetching card data…');
  const [setCards, stCards, sets] = await Promise.all([
    getJson<ApiCard[]>(`${API}/allSetCards/`),
    getJson<ApiCard[]>(`${API}/allSTCards/`),
    getJson<ApiSet[]>(`${API}/allSets/`),
  ]);

  // One row per printed leader card, keyed by its set code.
  const byCode = new Map<string, ApiCard>();
  for (const c of [...setCards, ...stCards]) {
    if (c.card_type !== 'Leader') continue;
    const prev = byCode.get(c.card_set_id);
    if (!prev || (isVariant(prev) && !isVariant(c))) byCode.set(c.card_set_id, c);
  }
  const cards = [...byCode.values()].sort((a, b) => a.card_set_id.localeCompare(b.card_set_id));
  console.log(`  ${cards.length} unique leaders`);

  await mkdir(IMAGE_DIR, { recursive: true });
  let downloaded = 0;
  for (const c of cards) {
    if (await fetchImage(c)) {
      downloaded += 1;
      process.stdout.write(`\r  images: ${downloaded} new`);
    }
  }
  console.log(`\r  images: ${downloaded} new, ${cards.length - downloaded} cached`);

  // Metas are the format-defining boosters OP01–OP16. The API reports OP-14 and
  // OP-15 under merged ids ("OP14-EB04"), so match on the leading OPnn.
  const metas = sets
    .map((s) => ({ code: /^OP-?(\d{2})/.exec(s.set_id)?.[1], name: s.set_name }))
    .filter((m): m is { code: string; name: string } => Boolean(m.code))
    .map((m) => ({ name: `OP${m.code} ${m.name}`, code: `OP${m.code}` }))
    .sort((a, b) => a.code.localeCompare(b.code));
  console.log(`  ${metas.length} metas`);

  // The single-colour starter decks (ST15–ST20, ST23–ST28) contain no new leader
  // cards — they reprint a booster leader with alternate art under its original
  // set code. Players still call those decks by their ST number, so index which
  // decks each leader ships in and let the picker search on that; otherwise
  // typing "ST17" finds nothing because that card is filed as OP01-060.
  const decks = await getJson<ApiDeck[]>(`${API}/allDecks/`);
  const deckCodes = new Map<string, string[]>();
  for (const d of decks) {
    const code = d.structure_deck_id.replace('-', '');
    const cardsInDeck = await getJson<ApiCard[]>(`${API}/decks/${d.structure_deck_id}/`);
    for (const c of cardsInDeck) {
      if (c.card_type !== 'Leader') continue;
      // Skip the deck's own numbering (ST01 → ST01-001 adds nothing to search).
      if (c.card_set_id.startsWith(code)) continue;
      const list = deckCodes.get(c.card_set_id) ?? [];
      if (!list.includes(code)) list.push(code);
      deckCodes.set(c.card_set_id, list);
    }
  }
  console.log(`  ${deckCodes.size} leaders reprinted in a starter deck`);

  const leaderRows = cards
    .map((c) => {
      const colors = parseColors(c.card_color).map((x) => `'${x}'`).join(', ');
      return `  { name: ${JSON.stringify(cleanLeaderName(c.card_name))}, colors: [${colors}], setCode: '${c.card_set_id}' },`;
    })
    .join('\n');

  await writeFile(
    path.join(ROOT, 'src/db/seed-data.ts'),
    BANNER('https://optcgapi.com') +
      '\nexport const SEED_LEADERS: { name: string; colors: string[]; setCode: string }[] = [\n' +
      leaderRows +
      '\n];\n\nexport const SEED_METAS: { name: string; code: string }[] = [\n' +
      metas.map((m) => `  { name: ${JSON.stringify(m.name)}, code: '${m.code}' },`).join('\n') +
      '\n];\n',
  );

  await writeFile(
    path.join(ROOT, 'src/lib/leader-images.ts'),
    BANNER('scripts/build-leader-data.ts') +
      '\n/** Leader set codes with bundled art in public/leaders/. */\n' +
      'export const LEADER_IMAGE_CODES: ReadonlySet<string> = new Set([\n' +
      cards.map((c) => `  '${c.card_set_id}',`).join('\n') +
      '\n]);\n\n' +
      '/**\n' +
      ' * Starter decks that reprint a leader under a different set code, so the\n' +
      " * picker can find OP01-060 when a player searches for their \"ST17\" deck.\n" +
      ' */\n' +
      'export const LEADER_DECK_CODES: Readonly<Record<string, readonly string[]>> = {\n' +
      [...deckCodes.entries()]
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([code, ds]) => `  '${code}': [${ds.sort().map((d) => `'${d}'`).join(', ')}],`)
        .join('\n') +
      '\n};\n',
  );

  console.log('Wrote src/db/seed-data.ts, src/lib/leader-images.ts, public/leaders/');
}

main().catch((e) => { console.error(e); process.exit(1); });
